django_basics_and_advanced/regularExam/regularExam/authors/urls.py
from django.urls import path

from regularExam.authors import views
from regularExam.authors.views import CreateAuthor

urlpatterns = {
    path('create/', CreateAuthor.as_view(), name='create-author'),
    path('edit/', views.edit_author, name='edit-author'),
    path('delete/', views.delete_author, name='delete-author'),
    path('details/', views.details_author, name='details-author'),
}

django_basics_and_advanced/regularExam/regularExam/common/urls.py
from django.urls import path

from regularExam.common import views

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

django_basics_and_advanced/regularExam/regularExam/posts/urls.py
from django.urls import path

from regularExam.posts import views

urlpatterns = {
    path('create/', views.create_post, name='create-post'),
    path('<post_id>/edit/ ', views.edit_post, name='edit-post'),
    path('<post_id>/delete/', views.delete_post, name='delete-post'),
    path('<post_id>/details/', views.details_post, name='details-post'),
}

django_basics_and_advanced/regularExam/regularExam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('regularExam.common.urls')),
    path('album/', include('regularExam.authors.urls')),
    path('profile/', include('regularExam.posts.urls')),
]

django_basics_and_advanced/regularExam/regularExam/authors/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from regularExam.authors.validators import AlphaValidator, ExactlyDigitsValidator


# Create your models here.


class Author(models.Model):
    first_name = models.CharField(
        max_length=40,
        validators=[
            MinLengthValidator(4),
            AlphaValidator(),
        ],
    )

    last_name = models.CharField(
        max_length=50,
        validators=[
            MinLengthValidator(2),
            AlphaValidator(),
        ],
    )

    # Todo: passwort input field
    passcode = models.CharField(
        max_length=6,
        validators=[
            ExactlyDigitsValidator(),
        ],
        help_text="Your passcode must be a combination of 6 digits"
    )

    pets_number = models.PositiveSmallIntegerField(
    )

    info = models.TextField(
        blank=True,
        null=True,
    )
    image_url = models.URLField(
        blank=True,
        null=True,
    )

django_basics_and_advanced/regularExam/regularExam/common/models.py
from django.db import models

# Create your models here.

django_basics_and_advanced/regularExam/regularExam/posts/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from regularExam.authors.models import Author


# Create your models here.


class Post(models.Model):
    title = models.CharField(
        max_length=50,
        unique=True,
        validators=[MinLengthValidator(5)],
        error_messages={
            'unique': "Oops! That title is already taken. How about something fresh and fun?"
        }
    )
    image_url = models.URLField(
        help_text="Share your funniest furry photo URL!",
    )
    content = models.TextField()

    # TODO: make it hidden in forms
    updated_at = models.DateTimeField(
        auto_now=True
    )

    # TODO: make it hidden in forms
    author = models.ForeignKey(
        Author,
        on_delete=models.CASCADE,
        related_name="posts"
    )

django_basics_and_advanced/regularExam/regularExam/authors/forms.py
from django import forms

from regularExam.authors.models import Author


class AuthorBaseForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = "__all__"


class AuthorCreateForm(AuthorBaseForm):
    pass

django_basics_and_advanced/regularExam/regularExam/authors/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView

from regularExam.authors.forms import AuthorCreateForm
from regularExam.authors.models import Author


# Create your views here.


class CreateAuthor(CreateView):
    model = Author
    form_class = AuthorCreateForm
    template_name = 'authors/create-author.html'
    success_url = reverse_lazy('dashboard')


def delete_author(request):
    return render(request, 'authors/delete-author.html')


def details_author(request):
    return render(request, 'authors/details-author.html')


def edit_author(request):
    return render(request, 'authors/edit-author.html')

django_basics_and_advanced/regularExam/regularExam/common/views.py
from django.shortcuts import render

from regularExam.authors.models import Author


# Create your views here.


def index(request):
    has_author_profile = Author.objects.first()

    return render(request, 'common/index.html', {
        'has_author_profile': has_author_profile
    })


def dashboard(request):
    posts = Author.objects.filter()
    return render(request, 'common/dashboard.html')

django_basics_and_advanced/regularExam/regularExam/posts/views.py
from django.shortcuts import render

# Create your views here.


def create_post(request):
    return render(request, 'posts/create-post.html')


def delete_post(request, post_id):
    return render(request, 'posts/delete-post.html')


def details_post(request, post_id):
    return render(request, 'posts/details-post.html')


def edit_post(request, post_id):
    return render(request, 'posts/edit-post.html')

django_basics_and_advanced/regularExam/templates/authors/create-author.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <!-- Create Author's Profile Form (Only if no author's profile has been created) -->
    <section id="register">
        <div class="form">
            <h2>Create Author's Profile</h2>

            <form class="register-form" method="post" action="">
                
                    {{ form }}
                    {% csrf_token %}

                <!-- form button -->
                <button type="submit">Create</button>
            </form>
        </div>
    </section>

{% endblock %}

django_basics_and_advanced/regularExam/templates/authors/delete-author.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
        <section id="edit">
          <div class="form">
            <h1>You are about to delete your Author's Profile</h1>
            <!-- Delete Author's Profile Form -->

            <form id="delete" class="register-form" method="" action="">
              <!-- Confirm Button -->
              <button type="submit">Confirm</button>
            </form>
          </div>
          <!-- End Delete Form -->
        </section>
{% endblock %}

django_basics_and_advanced/regularExam/templates/authors/details-author.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <!-- Author's Profile Details Section -->

    <section id="details">
        <div id="details-wrapper">
            <h2>Author's Profile Details</h2>

            <!-- if the author has provided a profile image link -->

            <img
                    id="details-img"
                    src="https://cdn.pixabay.com/photo/2016/03/31/19/56/avatar-1295395_1280.png"
                    alt="profile img"
            />

            <!-- if the author has NO profile image link -->
            <img
                    id="details-img"
                    src="/images/default.png"
                    alt="profile img"
            />

            <!-- author's full name -->
            <p id="details-title">Test User</p>

            <!-- number of posts -->
            <p id="nutrition">Published Posts: 3</p>

            <div id="info-wrapper">
                <div id="details-description">
                    <!-- pets number -->
                    <p>Pets Number: 4</p>

                    <!-- info if provided, otherwise skip the line -->
                    <p>Some funny info of me and all my pets</p>

                    <!-- Latest activity -->
                    <p>-------------------------------</p>
                    <!-- latest activity if there are posts: display the title of the last updated post -->
                    <p>
                        Last Updated Post:
                        <strong>My cool fluffy rabbits</strong>
                    </p>

                    <!-- latest activity if there are NO posts -->
                    <p>
                        Last Updated Post:
                        <strong>N/A</strong>
                    </p>
                </div>

                <!--Edit and Delete buttons -->
                <div id="action-buttons">
                    <a href="#" id="edit-btn">Edit</a>
                    <a href="#" id="delete-btn">Delete</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

django_basics_and_advanced/regularExam/templates/authors/edit-author.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <!-- Edit Author's Profile Form -->

    <section id="register">
        <div class="form">
            <h2>Edit Author's Profile</h2>

            <form class="register-form" method="" action="">
                <div>
                    <label for="id_first_name">First Name:</label>

                    <input
                            type="text"
                            name="first_name"
                            value="Test"
                            maxlength="40"
                            required
                            id="id_first_name"
                    />
                </div>

                <div>
                    <label for="id_last_name">Last Name:</label>

                    <input
                            type="text"
                            name="last_name"
                            value="User"
                            maxlength="50"
                            required
                            id="id_last_name"
                    />
                </div>

                <div>
                    <label for="id_pets_number">Pets Number:</label>

                    <input
                            type="number"
                            name="pets_number"
                            value="4"
                            min="0"
                            required
                            id="id_pets_number"
                    />
                </div>

                <div>
                    <label for="id_info">Info:</label>

                    <textarea name="info" cols="40" rows="10" id="id_info">
Some funny info of me and all my pets</textarea
                    >
                </div>

                <div>
                    <label for="id_image_url">Profile Image URL:</label>

                    <input
                            type="url"
                            name="image_url"
                            value="https://cdn.pixabay.com/photo/2016/03/31/19/56/avatar-1295395_1280.png"
                            maxlength="200"
                            id="id_image_url"
                    />
                </div>
                <!-- form button -->
                <button type="submit">Edit</button>
            </form>
        </div>
    </section>

{% endblock %}

django_basics_and_advanced/regularExam/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static '/styles/styles.css' %}"/>
    <title>FurryFunnies</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->

        <!-- Logo image: a link to index/home page -->
        <a id="logo" href="#">
            <img id="logo-img" src="{% static '/images/logo.png' %}" alt="logo"/>
        </a>

        <nav>
            <!-- If there is an author's profile -->
            {% if has_author_profile %}
            <div class="user">
                <a href="#">Dashboard</a>
                <a href="#">New Post</a>
                <a href="#">Author's Profile</a>
            </div>

            <!-- If author's profile has NOT been created -->
             {% else %}
            <div class="guest">
                <a href="#">Create Author's Profile</a>
            </div>
             {% endif %}
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>
</div>

<!-- footer -->
<footer>
    <p>&copy; 2024 FurryFunnies by SoftUni Team. All rights reserved.</p>
</footer>
</body>
</html>

django_basics_and_advanced/regularExam/templates/common/dashboard.html
{% extends 'base.html' %}
{% load static %}
        <!-- Dashboard page -->

        <!-- Display a heading if there are posts -->

{% block content %}
    
        <h2>Published Posts</h2>

        <!-- Display a heading if there are NO posts -->
        <h2>No published posts yet.</h2>

        <section id="dashboard">
          <!-- Display a div with information about each post (if any) -->

          <!-- first post -->
          <div class="post">
            <!-- post image -->
            <img
              src="https://cdn.pixabay.com/photo/2017/03/26/00/56/rabbit-2174679_1280.jpg"
              alt="My cool fluffy rabbits img"
            />
            <!-- post title -->
            <h3 class="title">My cool fluffy rabbits</h3>
            <!-- post content -->
            <p class="description">Adorable!</p>
            <!-- post details button -->
            <a class="details-btn" href="#">See More</a>
          </div>

          
          
        </section>

{% endblock %}

django_basics_and_advanced/regularExam/templates/common/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <section id="home">
        <h1>
            Share the Snuggles and Giggles <br/>Post Your Sweet Furry Moments!
        </h1>
        <img src="{% static '/images/cats.png' %}" alt="home"/>
    </section>


{% endblock %}

django_basics_and_advanced/regularExam/templates/posts/create-post.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
        <!-- Add Post Form -->
        <section id="create">
          <div class="form">
            <h2>New Post</h2>

            <form class="create-form" action="" method="">
              <div>
                <label for="id_title">Title:</label>

                <input
                  type="text"
                  name="title"
                  maxlength="50"
                  placeholder="Put an attractive and unique title..."
                  required
                  id="id_title"
                />
              </div>

              <div>
                <label for="id_image_url">Post Image URL:</label>

                <div class="helptext" id="id_image_url_helptext">
                  Share your funniest furry photo URL!
                </div>

                <input
                  type="url"
                  name="image_url"
                  maxlength="200"
                  required
                  aria-describedby="id_image_url_helptext"
                  id="id_image_url"
                />
              </div>

              <div>
                <label for="id_content">Content:</label>

                <textarea
                  name="content"
                  cols="40"
                  rows="10"
                  placeholder="Share some interesting facts about your adorable pets..."
                  required
                  id="id_content"
                ></textarea>
              </div>

              <!-- form button -->
              <button type="submit">Publish</button>
            </form>
          </div>
        </section>

{% endblock %}

django_basics_and_advanced/regularExam/templates/posts/delete-post.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <!-- Delete Post Form -->
    <section id="edit">
        <div class="form">
            <h2>Delete Post</h2>

            <form class="edit-form" method="" action="">
                <div>
                    <label for="id_title">Title:</label>

                    <input
                            type="text"
                            name="title"
                            value="My clever dog :)"
                            maxlength="50"
                            readonly="readonly"
                            required
                            id="id_title"
                    />
                </div>

                <div>
                    <label for="id_image_url">Post Image URL:</label>

                    <input
                            type="url"
                            name="image_url"
                            value="https://cdn.pixabay.com/photo/2024/04/05/19/04/ai-generated-8678034_1280.jpg"
                            maxlength="200"
                            readonly="readonly"
                            required
                            id="id_image_url"
                    />
                </div>

                <div>
                    <label for="id_content">Content:</label>

                    <textarea
                            name="content"
                            cols="40"
                            rows="10"
                            readonly="readonly"
                            required
                            id="id_content"
                    >
Einstein is the smartest dog ever!!!</textarea
                    >
                </div>

                <!-- form button -->
                <button type="submit">Delete</button>
            </form>
        </div>
    </section>

{% endblock %}

django_basics_and_advanced/regularExam/templates/posts/details-post.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <!-- Post Details -->
    <section id="details">
        <div id="details-wrapper">
            <h2>Post Details</h2>
            <!-- post image -->
            <img
                    id="details-img"
                    src="https://cdn.pixabay.com/photo/2024/04/05/19/04/ai-generated-8678034_1280.jpg"
                    alt="My clever dog :)"
            />
            <!-- post title -->
            <p id="details-title">My clever dog :)</p>
            <div id="info-wrapper">
                <div id="details-description">
                    <!-- post content -->
                    <p>Einstein is the smartest dog ever!!!</p>
                </div>

                <!--Edit and Delete buttons -->
                <div id="action-buttons">
                    <a href="#" id="edit-btn">Edit</a>
                    <a href="#" id="delete-btn">Delete</a>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

django_basics_and_advanced/regularExam/templates/posts/edit-post.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
        <!-- Edit Post Form -->
        <section id="edit">
          <div class="form">
            <h2>Edit Post</h2>

            <form class="edit-form" method="" action="">
              <div>
                <label for="id_title">Title:</label>

                <input
                  type="text"
                  name="title"
                  value="My clever dog :)"
                  maxlength="50"
                  required
                  id="id_title"
                />
              </div>

              <div>
                <label for="id_image_url">Post Image URL:</label>

                <input
                  type="url"
                  name="image_url"
                  value="https://cdn.pixabay.com/photo/2024/04/05/19/04/ai-generated-8678034_1280.jpg"
                  maxlength="200"
                  required
                  id="id_image_url"
                />
              </div>

              <div>
                <label for="id_content">Content:</label>

                <textarea
                  name="content"
                  cols="40"
                  rows="10"
                  required
                  id="id_content"
                >
Einstein is the smartest dog ever!!!</textarea
                >
              </div>

              <!-- form button -->
              <button type="submit">Edit</button>
            </form>
          </div>
        </section>

{% endblock %}